
           <form action="/signup">
                    <select onchange="this.form.submit()" name="locale" value=<?php echo isset($_GET['locale']) ? $_GET['locale'] : 'english'; ?>>

                        <option value="english" selected>English</option>
                        <option value="german">German</option>
                        <option value="hindi">Hindi</option>
                    </select>
                </form>
                <?php
                if (isset($_GET['locale'])) {
                    echo 'Language is set to ' . $_GET['locale'];
                }
                ?>

<h2><?php echo $this->locale->_('Sign up using this form'); ?></h2>

<?php 
    if(isset($message)){
        echo $message;
    }
?>
<?php echo $this->tag->form("signup/register"); ?>

    <p>
        <label for="name"><?php echo $this->locale->_('Name'); ?></label>
        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="email"><?php echo $this->locale->_('Email Address'); ?></label>
        <?php echo $this->tag->textField("email"); ?>
    </p>

    <p>
    <label for="role"><?php echo $this->locale->_('Choose a role'); ?></label>
    <select  name="role">
        <?php
        $dat=Roles::find();
        foreach( $dat as $k=>$v){
           
          ?>
        <option value="<?php echo $v->role ;?>"><?php echo $v->role; ?></option><?php } ?>
        
    </select><br>
    <br>  
    </p>

    <p>
        <?php echo $this->tag->submitButton("Register"); ?>
    </p>

</form>
<?php 
echo $this->tag->linkTo("user/login","Click here to Login");
?>









 

