
<h2>Sign up using this form</h2>

<?php 
    if(isset($message)){
        echo $message;
    }
?>
<?php echo $this->tag->form("signup/register"); ?>

    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>

    <p>
    <label for="role">CHOOSE A ROLE:</label>
    <select  name="role">
        <?php
        $dat=Roles::find();
        foreach( $dat as $k=>$v){
           
          ?>
        <option value="<?php echo $v->role ;?>"><?php echo $v->role; ?></option><?php } ?>
        
    </select><br>
    <br>  
    </p>

    <p>
        <?php echo $this->tag->submitButton("Registerr"); ?>
    </p>

</form>
<?php 
echo $this->tag->linkTo("user/login","Click here to Login");
?>









 

